name: Build SharpDump

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout SharpDump
      uses: actions/checkout@v3

    - name: Enable .NET Framework 3.5
      run: dism /online /enable-feature /featurename:NetFx3 /All /NoRestart
      shell: cmd

    - name: Build SharpDump with MSBuild
      run: msbuild SharpDump.csproj /p:Configuration=Release /p:Platform="Any CPU"
      shell: cmd

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SharpDump.exe
        path: SharpDump\bin\Release\SharpDump.exe
