name: Build SharpDump

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout SharpDump
      uses: actions/checkout@v3

    - name: Build SharpDump with dotnet CLI
      run: dotnet build ./SharpDump/SharpDump.csproj -c Release -r win-x64 --no-self-contained
      shell: cmd

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SharpDump.exe
        path: SharpDump\bin\Release\net7.0\win-x64\SharpDump.exe
