name: Build SharpDump

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout SharpDump
      uses: actions/checkout@v3

    - name: Install .NET Framework Developer Pack 3.5
      run: |
        Invoke-WebRequest https://download.microsoft.com/download/B/0/D/B0D6DF26-CE4F-4E08-8BFD-4D62B646C8D9/NDP35SP1-KB958484-x86-x64-AllOS-ENU.exe -OutFile install.exe
        .\install.exe /quiet /norestart
      shell: powershell

    - name: Build SharpDump with MSBuild
      run: msbuild SharpDump.csproj /p:Configuration=Release /p:Platform="Any CPU"
      shell: cmd

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SharpDump.exe
        path: SharpDump\bin\Release\SharpDump.exe
